on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  dart-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, macos-13, windows-latest ]

    steps:
      - uses: actions/checkout@v4
      - id: get-dart-version
        run: echo "dart_sdk_version=$(cat DART_SDK_VERSION)" >> $GITHUB_OUTPUT
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ steps.get-dart-version.outputs.dart_sdk_version }}
      - run: dart pub get
        working-directory: cli
      - run: dart test
        working-directory: cli
      - run: dart analyze
        working-directory: cli
      - run: dart compile exe bin/cli.dart
        working-directory: cli
