on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  cli-dart-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, macos-13, windows-latest ]

    steps:
      - uses: actions/checkout@v4
      - uses: pCYSl5EDgo/cat@master
        id: get-dart-version
        with:
          path: DART_SDK_VERSION
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ steps.get-dart-version.outputs.text }}
      - run: flutter pub get
        working-directory: ui
      - run: dart format . -o none --set-exit-if-changed
        working-directory: ui
      - run: flutter analyze --fatal-infos
        working-directory: ui
      - run: flutter test
        working-directory: ui
