on:
  push:
    branches: [ "main" ]
    paths:
      VERSION

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: getversion
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.getversion.outputs.version }}',
              sha: context.sha
            })
      - if: '!cancelled()'
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/TarasMazepa/homebrew-stax/actions/workflows/update.yml/dispatches \
            -f "inputs[tag]=${{ steps.getversion.outputs.version }}"
        env:
          GH_TOKEN: ${{ github.token }}
    
